{% set version = "4.1.2" %}

package:
  name: robotframework-pythonlibcore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-pythonlibcore/robotframework-pythonlibcore-{{ version }}.tar.gz
  sha256: 308c0f4afeed51d913f4883cd9eb2b002f4459a20d76b9c942a42cae0296ea26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - robotframework

test:
  imports:
    - robotlibcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotframework/PythonLibCore
  summary: Tools to ease creating larger test libraries for Robot Framework using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  description: |-
    The Robot Framework hybrid and dynamic library API gives more flexibility for
    library than the static library API, but they also sets requirements for
    libraries which needs to be implemented in the library side. PythonLibCore
    eases the problem by providing simpler interface and handling all the
    requirements towards the Robot Framework library APIs.

extra:
  recipe-maintainers:
    - bollwyvl
    - martinRenou
