{% set version = "4.4.1" %}

package:
  name: robotframework-pythonlibcore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-pythonlibcore/robotframework-pythonlibcore-{{ version }}.tar.gz
  sha256: 2d695b2ea906f5815179643e29182466675e682d82c5fa9d1009edfae2f84b16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - robotframework

test:
  imports:
    - robotlibcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotframework/PythonLibCore
  summary: Tools to ease creating larger test libraries for Robot Framework using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  description: |-
    The Robot Framework hybrid and dynamic library API gives more flexibility for
    library than the static library API, but they also sets requirements for
    libraries which needs to be implemented in the library side. PythonLibCore
    eases the problem by providing simpler interface and handling all the
    requirements towards the Robot Framework library APIs.

extra:
  recipe-maintainers:
    - bollwyvl
    - martinRenou
